// <auto-generated />
using System;
using Jellywatch.Api.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Jellywatch.Api.Migrations
{
    [DbContext(typeof(JellywatchDbContext))]
    [Migration("20260406155635_AddMediaImageLanguage")]
    partial class AddMediaImageLanguage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Jellywatch.Api.Domain.BlacklistedItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("JellyfinItemId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BlacklistedItems");
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.Episode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("AirDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("air_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("EpisodeNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("episode_number");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Overview")
                        .HasColumnType("TEXT")
                        .HasColumnName("overview");

                    b.Property<int?>("Runtime")
                        .HasColumnType("INTEGER")
                        .HasColumnName("runtime");

                    b.Property<int>("SeasonId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("season_id");

                    b.Property<string>("StillPath")
                        .HasColumnType("TEXT")
                        .HasColumnName("still_path");

                    b.Property<int?>("TmdbId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tmdb_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId");

                    b.ToTable("episode", (string)null);
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.ExternalRating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("MediaItemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("media_item_id");

                    b.Property<int>("Provider")
                        .HasColumnType("INTEGER")
                        .HasColumnName("provider");

                    b.Property<string>("Score")
                        .HasColumnType("TEXT")
                        .HasColumnName("score");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<int?>("VoteCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("vote_count");

                    b.HasKey("Id");

                    b.HasIndex("MediaItemId", "Provider")
                        .IsUnique();

                    b.ToTable("external_rating", (string)null);
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.ImportQueueItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("JellyfinItemId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("jellyfin_item_id");

                    b.Property<int>("MediaType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("media_type");

                    b.Property<DateTime?>("NextRetryAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("next_retry_at");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER")
                        .HasColumnName("priority");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("retry_count");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("JellyfinItemId");

                    b.HasIndex("Status");

                    b.ToTable("import_queue_item", (string)null);
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.JellyfinLibraryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("JellyfinItemId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("jellyfin_item_id");

                    b.Property<string>("JellyfinParentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("jellyfin_parent_id");

                    b.Property<int?>("MediaItemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("media_item_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int?>("Type")
                        .HasColumnType("INTEGER")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("JellyfinItemId")
                        .IsUnique();

                    b.HasIndex("MediaItemId");

                    b.ToTable("jellyfin_library_item", (string)null);
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.MediaImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int?>("EpisodeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("episode_id");

                    b.Property<int?>("Height")
                        .HasColumnType("INTEGER")
                        .HasColumnName("height");

                    b.Property<int>("ImageType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("image_type");

                    b.Property<string>("Language")
                        .HasColumnType("TEXT")
                        .HasColumnName("language");

                    b.Property<string>("LocalPath")
                        .HasColumnType("TEXT")
                        .HasColumnName("local_path");

                    b.Property<int>("MediaItemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("media_item_id");

                    b.Property<string>("RemoteUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("remote_url");

                    b.Property<int?>("SeasonId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("season_id");

                    b.Property<int?>("Width")
                        .HasColumnType("INTEGER")
                        .HasColumnName("width");

                    b.HasKey("Id");

                    b.HasIndex("EpisodeId");

                    b.HasIndex("MediaItemId");

                    b.HasIndex("SeasonId");

                    b.ToTable("media_image", (string)null);
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.MediaItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("BackdropPath")
                        .HasColumnType("TEXT")
                        .HasColumnName("backdrop_path");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("ImdbId")
                        .HasColumnType("TEXT")
                        .HasColumnName("imdb_id");

                    b.Property<int>("MediaType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("media_type");

                    b.Property<string>("OriginalLanguage")
                        .HasColumnType("TEXT")
                        .HasColumnName("original_language");

                    b.Property<string>("OriginalTitle")
                        .HasColumnType("TEXT")
                        .HasColumnName("original_title");

                    b.Property<string>("Overview")
                        .HasColumnType("TEXT")
                        .HasColumnName("overview");

                    b.Property<string>("PosterPath")
                        .HasColumnType("TEXT")
                        .HasColumnName("poster_path");

                    b.Property<string>("ReleaseDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("release_date");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<int?>("TmdbId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tmdb_id");

                    b.Property<int?>("TvMazeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tvmaze_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ImdbId");

                    b.HasIndex("TmdbId");

                    b.HasIndex("TvMazeId");

                    b.ToTable("media_item", (string)null);
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.MediaTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("language");

                    b.Property<int>("MediaItemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("media_item_id");

                    b.Property<string>("Overview")
                        .HasColumnType("TEXT")
                        .HasColumnName("overview");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("MediaItemId", "Language")
                        .IsUnique();

                    b.ToTable("media_translation", (string)null);
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.MetadataRefreshJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime?>("LastRefreshed")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_refreshed");

                    b.Property<int>("MediaItemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("media_item_id");

                    b.Property<DateTime?>("NextRefresh")
                        .HasColumnType("TEXT")
                        .HasColumnName("next_refresh");

                    b.Property<int>("Provider")
                        .HasColumnType("INTEGER")
                        .HasColumnName("provider");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("MediaItemId");

                    b.ToTable("metadata_refresh_job", (string)null);
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("MediaItemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("media_item_id");

                    b.Property<int?>("Runtime")
                        .HasColumnType("INTEGER")
                        .HasColumnName("runtime");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("MediaItemId")
                        .IsUnique();

                    b.ToTable("movie", (string)null);
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsJoint")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_joint");

                    b.Property<string>("JellyfinUserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("jellyfin_user_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("JellyfinUserId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("profile", (string)null);
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.ProfileNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int?>("EpisodeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("episode_id");

                    b.Property<int>("MediaItemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("media_item_id");

                    b.Property<int>("ProfileId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("profile_id");

                    b.Property<int?>("SeasonId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("season_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("EpisodeId");

                    b.HasIndex("MediaItemId");

                    b.HasIndex("SeasonId");

                    b.HasIndex("ProfileId", "MediaItemId", "SeasonId", "EpisodeId")
                        .IsUnique();

                    b.ToTable("profile_note", (string)null);
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.ProfileWatchState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int?>("EpisodeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("episode_id");

                    b.Property<bool>("IsManualOverride")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_manual_override");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_updated");

                    b.Property<int>("MediaItemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("media_item_id");

                    b.Property<int?>("MovieId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("movie_id");

                    b.Property<int>("ProfileId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("profile_id");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER")
                        .HasColumnName("state");

                    b.HasKey("Id");

                    b.HasIndex("EpisodeId");

                    b.HasIndex("MediaItemId");

                    b.HasIndex("MovieId");

                    b.HasIndex("ProfileId", "MediaItemId", "EpisodeId", "MovieId")
                        .IsUnique();

                    b.ToTable("profile_watch_state", (string)null);
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.PropagationRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<int>("SourceProfileId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("source_profile_id");

                    b.Property<int>("TargetProfileId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("target_profile_id");

                    b.HasKey("Id");

                    b.HasIndex("TargetProfileId");

                    b.HasIndex("SourceProfileId", "TargetProfileId")
                        .IsUnique();

                    b.ToTable("propagation_rule", (string)null);
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.ProviderCacheEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CachedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("cached_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("expires_at");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("external_id");

                    b.Property<int>("Provider")
                        .HasColumnType("INTEGER")
                        .HasColumnName("provider");

                    b.Property<string>("ResponseJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("response_json");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("Provider", "ExternalId")
                        .IsUnique();

                    b.ToTable("provider_cache_entry", (string)null);
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.Season", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("AirDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("air_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int?>("EpisodeCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("episode_count");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Overview")
                        .HasColumnType("TEXT")
                        .HasColumnName("overview");

                    b.Property<string>("PosterPath")
                        .HasColumnType("TEXT")
                        .HasColumnName("poster_path");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("season_number");

                    b.Property<int>("SeriesId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("series_id");

                    b.Property<int?>("TmdbId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tmdb_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("SeriesId");

                    b.ToTable("season", (string)null);
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.Series", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("MediaItemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("media_item_id");

                    b.Property<string>("Network")
                        .HasColumnType("TEXT")
                        .HasColumnName("network");

                    b.Property<int?>("TotalEpisodes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_episodes");

                    b.Property<int?>("TotalSeasons")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_seasons");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("MediaItemId")
                        .IsUnique();

                    b.ToTable("series", (string)null);
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.SyncJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("completed_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT")
                        .HasColumnName("error_message");

                    b.Property<int>("ItemsProcessed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("items_processed");

                    b.Property<int?>("ProfileId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("profile_id");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("sync_job", (string)null);
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_admin");

                    b.Property<string>("JellyfinServerUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("JellyfinUserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("jellyfin_user_id");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("preferred_language");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("JellyfinUserId")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.WatchEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int?>("EpisodeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("episode_id");

                    b.Property<int>("EventType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("event_type");

                    b.Property<string>("JellyfinItemId")
                        .HasColumnType("TEXT")
                        .HasColumnName("jellyfin_item_id");

                    b.Property<int>("MediaItemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("media_item_id");

                    b.Property<int?>("MovieId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("movie_id");

                    b.Property<long?>("PositionTicks")
                        .HasColumnType("INTEGER")
                        .HasColumnName("position_ticks");

                    b.Property<int>("ProfileId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("profile_id");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER")
                        .HasColumnName("source");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT")
                        .HasColumnName("timestamp");

                    b.HasKey("Id");

                    b.HasIndex("EpisodeId");

                    b.HasIndex("JellyfinItemId");

                    b.HasIndex("MediaItemId");

                    b.HasIndex("MovieId");

                    b.HasIndex("ProfileId");

                    b.HasIndex("Timestamp");

                    b.ToTable("watch_event", (string)null);
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.WebhookEventLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT")
                        .HasColumnName("error_message");

                    b.Property<string>("EventType")
                        .HasColumnType("TEXT")
                        .HasColumnName("event_type");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("processed_at");

                    b.Property<string>("RawPayload")
                        .HasColumnType("TEXT")
                        .HasColumnName("raw_payload");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("received_at");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER")
                        .HasColumnName("success");

                    b.HasKey("Id");

                    b.ToTable("webhook_event_log", (string)null);
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.Episode", b =>
                {
                    b.HasOne("Jellywatch.Api.Domain.Season", "Season")
                        .WithMany("Episodes")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.ExternalRating", b =>
                {
                    b.HasOne("Jellywatch.Api.Domain.MediaItem", "MediaItem")
                        .WithMany("ExternalRatings")
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaItem");
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.JellyfinLibraryItem", b =>
                {
                    b.HasOne("Jellywatch.Api.Domain.MediaItem", "MediaItem")
                        .WithMany()
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("MediaItem");
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.MediaImage", b =>
                {
                    b.HasOne("Jellywatch.Api.Domain.Episode", "Episode")
                        .WithMany()
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Jellywatch.Api.Domain.MediaItem", "MediaItem")
                        .WithMany("Images")
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jellywatch.Api.Domain.Season", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Episode");

                    b.Navigation("MediaItem");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.MediaTranslation", b =>
                {
                    b.HasOne("Jellywatch.Api.Domain.MediaItem", "MediaItem")
                        .WithMany("Translations")
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaItem");
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.MetadataRefreshJob", b =>
                {
                    b.HasOne("Jellywatch.Api.Domain.MediaItem", "MediaItem")
                        .WithMany()
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaItem");
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.Movie", b =>
                {
                    b.HasOne("Jellywatch.Api.Domain.MediaItem", "MediaItem")
                        .WithOne("Movie")
                        .HasForeignKey("Jellywatch.Api.Domain.Movie", "MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaItem");
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.Profile", b =>
                {
                    b.HasOne("Jellywatch.Api.Domain.User", "User")
                        .WithMany("Profiles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.ProfileNote", b =>
                {
                    b.HasOne("Jellywatch.Api.Domain.Episode", "Episode")
                        .WithMany("Notes")
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Jellywatch.Api.Domain.MediaItem", "MediaItem")
                        .WithMany("Notes")
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jellywatch.Api.Domain.Profile", "Profile")
                        .WithMany("Notes")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jellywatch.Api.Domain.Season", "Season")
                        .WithMany("Notes")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Episode");

                    b.Navigation("MediaItem");

                    b.Navigation("Profile");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.ProfileWatchState", b =>
                {
                    b.HasOne("Jellywatch.Api.Domain.Episode", "Episode")
                        .WithMany("WatchStates")
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Jellywatch.Api.Domain.MediaItem", "MediaItem")
                        .WithMany("WatchStates")
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jellywatch.Api.Domain.Movie", "Movie")
                        .WithMany("WatchStates")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Jellywatch.Api.Domain.Profile", "Profile")
                        .WithMany("WatchStates")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Episode");

                    b.Navigation("MediaItem");

                    b.Navigation("Movie");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.PropagationRule", b =>
                {
                    b.HasOne("Jellywatch.Api.Domain.Profile", "SourceProfile")
                        .WithMany("SourceRules")
                        .HasForeignKey("SourceProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jellywatch.Api.Domain.Profile", "TargetProfile")
                        .WithMany("TargetRules")
                        .HasForeignKey("TargetProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourceProfile");

                    b.Navigation("TargetProfile");
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.Season", b =>
                {
                    b.HasOne("Jellywatch.Api.Domain.Series", "Series")
                        .WithMany("Seasons")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Series");
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.Series", b =>
                {
                    b.HasOne("Jellywatch.Api.Domain.MediaItem", "MediaItem")
                        .WithOne("Series")
                        .HasForeignKey("Jellywatch.Api.Domain.Series", "MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaItem");
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.SyncJob", b =>
                {
                    b.HasOne("Jellywatch.Api.Domain.Profile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.WatchEvent", b =>
                {
                    b.HasOne("Jellywatch.Api.Domain.Episode", "Episode")
                        .WithMany("WatchEvents")
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Jellywatch.Api.Domain.MediaItem", "MediaItem")
                        .WithMany()
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jellywatch.Api.Domain.Movie", "Movie")
                        .WithMany("WatchEvents")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Jellywatch.Api.Domain.Profile", "Profile")
                        .WithMany("WatchEvents")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Episode");

                    b.Navigation("MediaItem");

                    b.Navigation("Movie");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.Episode", b =>
                {
                    b.Navigation("Notes");

                    b.Navigation("WatchEvents");

                    b.Navigation("WatchStates");
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.MediaItem", b =>
                {
                    b.Navigation("ExternalRatings");

                    b.Navigation("Images");

                    b.Navigation("Movie");

                    b.Navigation("Notes");

                    b.Navigation("Series");

                    b.Navigation("Translations");

                    b.Navigation("WatchStates");
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.Movie", b =>
                {
                    b.Navigation("WatchEvents");

                    b.Navigation("WatchStates");
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.Profile", b =>
                {
                    b.Navigation("Notes");

                    b.Navigation("SourceRules");

                    b.Navigation("TargetRules");

                    b.Navigation("WatchEvents");

                    b.Navigation("WatchStates");
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.Season", b =>
                {
                    b.Navigation("Episodes");

                    b.Navigation("Notes");
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.Series", b =>
                {
                    b.Navigation("Seasons");
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.User", b =>
                {
                    b.Navigation("Profiles");
                });
#pragma warning restore 612, 618
        }
    }
}
