// <auto-generated />
using System;
using Jellywatch.Api.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Jellywatch.Api.Migrations
{
    [DbContext(typeof(JellywatchDbContext))]
    partial class JellywatchDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Jellywatch.Api.Domain.BackupSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("BackupHour")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(3)
                        .HasColumnName("backup_hour");

                    b.Property<int>("BackupMinute")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("backup_minute");

                    b.Property<string>("DestinationPath")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("/backups")
                        .HasColumnName("destination_path");

                    b.Property<string>("FileNamePrefix")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("")
                        .HasColumnName("file_name_prefix");

                    b.Property<string>("FileNameSuffix")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("")
                        .HasColumnName("file_name_suffix");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("is_enabled");

                    b.Property<DateTime?>("LastRunAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_run_at");

                    b.Property<string>("LastRunMessage")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_run_message");

                    b.Property<string>("LastRunStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("never")
                        .HasColumnName("last_run_status");

                    b.Property<int>("RetentionCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(7)
                        .HasColumnName("retention_count");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("backup_schedule", (string)null);
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.BlacklistedItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("JellyfinItemId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BlacklistedItems", (string)null);
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.Episode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("AirDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("air_date");

                    b.Property<string>("AirTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("air_time");

                    b.Property<string>("AirTimeUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("air_time_utc");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("EpisodeNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("episode_number");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Overview")
                        .HasColumnType("TEXT")
                        .HasColumnName("overview");

                    b.Property<int?>("Runtime")
                        .HasColumnType("INTEGER")
                        .HasColumnName("runtime");

                    b.Property<int>("SeasonId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("season_id");

                    b.Property<string>("StillPath")
                        .HasColumnType("TEXT")
                        .HasColumnName("still_path");

                    b.Property<int?>("TmdbId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tmdb_id");

                    b.Property<double?>("TmdbRating")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId");

                    b.ToTable("episode", (string)null);
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.ExternalRating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("MediaItemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("media_item_id");

                    b.Property<int>("Provider")
                        .HasColumnType("INTEGER")
                        .HasColumnName("provider");

                    b.Property<string>("Score")
                        .HasColumnType("TEXT")
                        .HasColumnName("score");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<int?>("VoteCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("vote_count");

                    b.HasKey("Id");

                    b.HasIndex("MediaItemId", "Provider")
                        .IsUnique();

                    b.ToTable("external_rating", (string)null);
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.ImportQueueItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("JellyfinItemId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("jellyfin_item_id");

                    b.Property<int>("MediaType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("media_type");

                    b.Property<DateTime?>("NextRetryAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("next_retry_at");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER")
                        .HasColumnName("priority");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("retry_count");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("JellyfinItemId");

                    b.HasIndex("Status");

                    b.ToTable("import_queue_item", (string)null);
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.JellyfinLibraryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("JellyfinItemId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("jellyfin_item_id");

                    b.Property<string>("JellyfinParentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("jellyfin_parent_id");

                    b.Property<int?>("MediaItemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("media_item_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int?>("Type")
                        .HasColumnType("INTEGER")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("JellyfinItemId")
                        .IsUnique();

                    b.HasIndex("MediaItemId");

                    b.ToTable("jellyfin_library_item", (string)null);
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.MediaImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int?>("EpisodeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("episode_id");

                    b.Property<int?>("Height")
                        .HasColumnType("INTEGER")
                        .HasColumnName("height");

                    b.Property<int>("ImageType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("image_type");

                    b.Property<string>("Language")
                        .HasColumnType("TEXT")
                        .HasColumnName("language");

                    b.Property<string>("LocalPath")
                        .HasColumnType("TEXT")
                        .HasColumnName("local_path");

                    b.Property<int>("MediaItemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("media_item_id");

                    b.Property<string>("RemoteUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("remote_url");

                    b.Property<int?>("SeasonId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("season_id");

                    b.Property<int?>("Width")
                        .HasColumnType("INTEGER")
                        .HasColumnName("width");

                    b.HasKey("Id");

                    b.HasIndex("EpisodeId");

                    b.HasIndex("MediaItemId");

                    b.HasIndex("SeasonId");

                    b.ToTable("media_image", (string)null);
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.MediaItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("BackdropPath")
                        .HasColumnType("TEXT")
                        .HasColumnName("backdrop_path");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Genres")
                        .HasColumnType("TEXT")
                        .HasColumnName("genres");

                    b.Property<string>("ImdbId")
                        .HasColumnType("TEXT")
                        .HasColumnName("imdb_id");

                    b.Property<int>("MediaType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("media_type");

                    b.Property<string>("OriginalLanguage")
                        .HasColumnType("TEXT")
                        .HasColumnName("original_language");

                    b.Property<string>("OriginalTitle")
                        .HasColumnType("TEXT")
                        .HasColumnName("original_title");

                    b.Property<string>("Overview")
                        .HasColumnType("TEXT")
                        .HasColumnName("overview");

                    b.Property<string>("PosterPath")
                        .HasColumnType("TEXT")
                        .HasColumnName("poster_path");

                    b.Property<string>("ReleaseDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("release_date");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<int?>("TmdbId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tmdb_id");

                    b.Property<int?>("TvMazeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tvmaze_id");

                    b.Property<int?>("TvdbId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tvdb_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ImdbId");

                    b.HasIndex("TmdbId");

                    b.HasIndex("TvMazeId");

                    b.HasIndex("TvdbId");

                    b.ToTable("media_item", (string)null);
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.MediaTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("language");

                    b.Property<int>("MediaItemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("media_item_id");

                    b.Property<string>("Overview")
                        .HasColumnType("TEXT")
                        .HasColumnName("overview");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("MediaItemId", "Language")
                        .IsUnique();

                    b.ToTable("media_translation", (string)null);
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.MetadataRefreshJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime?>("LastRefreshed")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_refreshed");

                    b.Property<int>("MediaItemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("media_item_id");

                    b.Property<DateTime?>("NextRefresh")
                        .HasColumnType("TEXT")
                        .HasColumnName("next_refresh");

                    b.Property<int>("Provider")
                        .HasColumnType("INTEGER")
                        .HasColumnName("provider");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("MediaItemId");

                    b.ToTable("metadata_refresh_job", (string)null);
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("MediaItemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("media_item_id");

                    b.Property<int?>("Runtime")
                        .HasColumnType("INTEGER")
                        .HasColumnName("runtime");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("MediaItemId")
                        .IsUnique();

                    b.ToTable("movie", (string)null);
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsJoint")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_joint");

                    b.Property<string>("JellyfinUserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("jellyfin_user_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("JellyfinUserId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("profile", (string)null);
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.ProfileMediaBlock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MediaItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProfileId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MediaItemId");

                    b.HasIndex("ProfileId");

                    b.ToTable("ProfileMediaBlocks", (string)null);
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.ProfileNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int?>("EpisodeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("episode_id");

                    b.Property<int>("MediaItemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("media_item_id");

                    b.Property<int>("ProfileId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("profile_id");

                    b.Property<int?>("SeasonId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("season_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("EpisodeId");

                    b.HasIndex("MediaItemId");

                    b.HasIndex("SeasonId");

                    b.HasIndex("ProfileId", "MediaItemId", "SeasonId", "EpisodeId")
                        .IsUnique();

                    b.ToTable("profile_note", (string)null);
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.ProfileWatchState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int?>("EpisodeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("episode_id");

                    b.Property<bool>("ExcludeFromDashboard")
                        .HasColumnType("INTEGER")
                        .HasColumnName("exclude_from_dashboard");

                    b.Property<bool>("IncludeInDashboard")
                        .HasColumnType("INTEGER")
                        .HasColumnName("include_in_dashboard");

                    b.Property<bool>("IsManualOverride")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_manual_override");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_updated");

                    b.Property<int>("MediaItemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("media_item_id");

                    b.Property<int?>("MovieId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("movie_id");

                    b.Property<int>("ProfileId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("profile_id");

                    b.Property<int?>("SeasonId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("season_id");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER")
                        .HasColumnName("state");

                    b.Property<decimal?>("UserRating")
                        .HasColumnType("decimal(4,2)")
                        .HasColumnName("user_rating");

                    b.HasKey("Id");

                    b.HasIndex("EpisodeId");

                    b.HasIndex("MediaItemId");

                    b.HasIndex("MovieId");

                    b.HasIndex("SeasonId");

                    b.HasIndex("ProfileId", "MediaItemId", "EpisodeId", "SeasonId", "MovieId")
                        .IsUnique();

                    b.ToTable("profile_watch_state", (string)null);
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.PropagationRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<int>("SourceProfileId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("source_profile_id");

                    b.Property<int>("TargetProfileId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("target_profile_id");

                    b.HasKey("Id");

                    b.HasIndex("TargetProfileId");

                    b.HasIndex("SourceProfileId", "TargetProfileId")
                        .IsUnique();

                    b.ToTable("propagation_rule", (string)null);
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.ProviderCacheEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CachedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("cached_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("expires_at");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("external_id");

                    b.Property<int>("Provider")
                        .HasColumnType("INTEGER")
                        .HasColumnName("provider");

                    b.Property<string>("ResponseJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("response_json");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("Provider", "ExternalId")
                        .IsUnique();

                    b.ToTable("provider_cache_entry", (string)null);
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.Season", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("AirDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("air_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int?>("EpisodeCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("episode_count");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Overview")
                        .HasColumnType("TEXT")
                        .HasColumnName("overview");

                    b.Property<string>("PosterPath")
                        .HasColumnType("TEXT")
                        .HasColumnName("poster_path");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("season_number");

                    b.Property<int>("SeriesId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("series_id");

                    b.Property<int?>("TmdbId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tmdb_id");

                    b.Property<double?>("TmdbRating")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("SeriesId");

                    b.ToTable("season", (string)null);
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.Series", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("MediaItemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("media_item_id");

                    b.Property<string>("Network")
                        .HasColumnType("TEXT")
                        .HasColumnName("network");

                    b.Property<int?>("TotalEpisodes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_episodes");

                    b.Property<int?>("TotalSeasons")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_seasons");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("MediaItemId")
                        .IsUnique();

                    b.ToTable("series", (string)null);
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.SyncJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("completed_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT")
                        .HasColumnName("error_message");

                    b.Property<int>("ItemsProcessed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("items_processed");

                    b.Property<int?>("ProfileId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("profile_id");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("sync_job", (string)null);
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_admin");

                    b.Property<string>("JellyfinServerUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("JellyfinUserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("jellyfin_user_id");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("preferred_language");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("JellyfinUserId")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.UserWatchlistPreference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int?>("DefaultWatchlistId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("default_watchlist_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("DefaultWatchlistId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("user_watchlist_preference", (string)null);
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.WatchEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EpisodeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("episode_id");

                    b.Property<int>("EventType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("event_type");

                    b.Property<string>("JellyfinItemId")
                        .HasColumnType("TEXT")
                        .HasColumnName("jellyfin_item_id");

                    b.Property<int>("MediaItemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("media_item_id");

                    b.Property<int?>("MovieId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("movie_id");

                    b.Property<long?>("PositionTicks")
                        .HasColumnType("INTEGER")
                        .HasColumnName("position_ticks");

                    b.Property<int>("ProfileId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("profile_id");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER")
                        .HasColumnName("source");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT")
                        .HasColumnName("timestamp");

                    b.HasKey("Id");

                    b.HasIndex("EpisodeId");

                    b.HasIndex("JellyfinItemId");

                    b.HasIndex("MediaItemId");

                    b.HasIndex("MovieId");

                    b.HasIndex("ProfileId");

                    b.HasIndex("Timestamp");

                    b.ToTable("watch_event", (string)null);
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.Watchlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("OwnerUserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("owner_user_id");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER")
                        .HasColumnName("state");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("watchlist", (string)null);
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.WatchlistAccessRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Message")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("message");

                    b.Property<int>("RequestingUserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("requesting_user_id");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("responded_at");

                    b.Property<int?>("RespondedByUserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("responded_by_user_id");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status");

                    b.Property<int>("WatchlistId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("watchlist_id");

                    b.HasKey("Id");

                    b.HasIndex("RequestingUserId");

                    b.HasIndex("RespondedByUserId");

                    b.HasIndex("WatchlistId", "RequestingUserId", "Status");

                    b.ToTable("watchlist_access_request", (string)null);
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.WatchlistInvitation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<bool>("CanAddItems")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("can_add_items");

                    b.Property<bool>("CanInviteMembers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("can_invite_members");

                    b.Property<bool>("CanManageMembers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("can_manage_members");

                    b.Property<bool>("CanRemoveItems")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("can_remove_items");

                    b.Property<bool>("CanReorderItems")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("can_reorder_items");

                    b.Property<bool>("CanUpdateItemStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("can_update_item_status");

                    b.Property<bool>("CanUpdateWatchlist")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("can_update_watchlist");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("InvitedByUserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("invited_by_user_id");

                    b.Property<int>("InvitedUserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("invited_user_id");

                    b.Property<string>("Message")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("message");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("responded_at");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER")
                        .HasColumnName("role");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status");

                    b.Property<int>("WatchlistId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("watchlist_id");

                    b.HasKey("Id");

                    b.HasIndex("InvitedByUserId");

                    b.HasIndex("InvitedUserId");

                    b.HasIndex("WatchlistId", "InvitedUserId", "Status");

                    b.ToTable("watchlist_invitation", (string)null);
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.WatchlistItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int?>("AddedByUserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("added_by_user_id");

                    b.Property<int?>("ChildWatchlistId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("child_watchlist_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("ItemType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("item_type");

                    b.Property<int?>("MediaItemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("media_item_id");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER")
                        .HasColumnName("position");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<int>("WatchlistId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("watchlist_id");

                    b.HasKey("Id");

                    b.HasIndex("AddedByUserId");

                    b.HasIndex("ChildWatchlistId");

                    b.HasIndex("MediaItemId");

                    b.HasIndex("WatchlistId", "ChildWatchlistId")
                        .IsUnique()
                        .HasFilter("child_watchlist_id IS NOT NULL");

                    b.HasIndex("WatchlistId", "MediaItemId")
                        .IsUnique()
                        .HasFilter("media_item_id IS NOT NULL");

                    b.HasIndex("WatchlistId", "Position");

                    b.ToTable("watchlist_item", (string)null);
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.WatchlistMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<bool>("CanAddItems")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("can_add_items");

                    b.Property<bool>("CanInviteMembers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("can_invite_members");

                    b.Property<bool>("CanManageMembers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("can_manage_members");

                    b.Property<bool>("CanRemoveItems")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("can_remove_items");

                    b.Property<bool>("CanReorderItems")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("can_reorder_items");

                    b.Property<bool>("CanUpdateItemStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("can_update_item_status");

                    b.Property<bool>("CanUpdateWatchlist")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("can_update_watchlist");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int?>("InvitedByUserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("invited_by_user_id");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.Property<int>("WatchlistId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("watchlist_id");

                    b.HasKey("Id");

                    b.HasIndex("InvitedByUserId");

                    b.HasIndex("UserId");

                    b.HasIndex("WatchlistId", "UserId")
                        .IsUnique();

                    b.ToTable("watchlist_member", (string)null);
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.WebhookEventLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT")
                        .HasColumnName("error_message");

                    b.Property<string>("EventType")
                        .HasColumnType("TEXT")
                        .HasColumnName("event_type");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("processed_at");

                    b.Property<string>("RawPayload")
                        .HasColumnType("TEXT")
                        .HasColumnName("raw_payload");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("received_at");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER")
                        .HasColumnName("success");

                    b.HasKey("Id");

                    b.ToTable("webhook_event_log", (string)null);
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.BackupSchedule", b =>
                {
                    b.HasOne("Jellywatch.Api.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.Episode", b =>
                {
                    b.HasOne("Jellywatch.Api.Domain.Season", "Season")
                        .WithMany("Episodes")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.ExternalRating", b =>
                {
                    b.HasOne("Jellywatch.Api.Domain.MediaItem", "MediaItem")
                        .WithMany("ExternalRatings")
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaItem");
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.JellyfinLibraryItem", b =>
                {
                    b.HasOne("Jellywatch.Api.Domain.MediaItem", "MediaItem")
                        .WithMany()
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("MediaItem");
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.MediaImage", b =>
                {
                    b.HasOne("Jellywatch.Api.Domain.Episode", "Episode")
                        .WithMany()
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Jellywatch.Api.Domain.MediaItem", "MediaItem")
                        .WithMany("Images")
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jellywatch.Api.Domain.Season", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Episode");

                    b.Navigation("MediaItem");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.MediaTranslation", b =>
                {
                    b.HasOne("Jellywatch.Api.Domain.MediaItem", "MediaItem")
                        .WithMany("Translations")
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaItem");
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.MetadataRefreshJob", b =>
                {
                    b.HasOne("Jellywatch.Api.Domain.MediaItem", "MediaItem")
                        .WithMany()
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaItem");
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.Movie", b =>
                {
                    b.HasOne("Jellywatch.Api.Domain.MediaItem", "MediaItem")
                        .WithOne("Movie")
                        .HasForeignKey("Jellywatch.Api.Domain.Movie", "MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaItem");
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.Profile", b =>
                {
                    b.HasOne("Jellywatch.Api.Domain.User", "User")
                        .WithMany("Profiles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.ProfileMediaBlock", b =>
                {
                    b.HasOne("Jellywatch.Api.Domain.MediaItem", "MediaItem")
                        .WithMany()
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jellywatch.Api.Domain.Profile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaItem");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.ProfileNote", b =>
                {
                    b.HasOne("Jellywatch.Api.Domain.Episode", "Episode")
                        .WithMany("Notes")
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Jellywatch.Api.Domain.MediaItem", "MediaItem")
                        .WithMany("Notes")
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jellywatch.Api.Domain.Profile", "Profile")
                        .WithMany("Notes")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jellywatch.Api.Domain.Season", "Season")
                        .WithMany("Notes")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Episode");

                    b.Navigation("MediaItem");

                    b.Navigation("Profile");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.ProfileWatchState", b =>
                {
                    b.HasOne("Jellywatch.Api.Domain.Episode", "Episode")
                        .WithMany("WatchStates")
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Jellywatch.Api.Domain.MediaItem", "MediaItem")
                        .WithMany("WatchStates")
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jellywatch.Api.Domain.Movie", "Movie")
                        .WithMany("WatchStates")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Jellywatch.Api.Domain.Profile", "Profile")
                        .WithMany("WatchStates")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jellywatch.Api.Domain.Season", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Episode");

                    b.Navigation("MediaItem");

                    b.Navigation("Movie");

                    b.Navigation("Profile");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.PropagationRule", b =>
                {
                    b.HasOne("Jellywatch.Api.Domain.Profile", "SourceProfile")
                        .WithMany("SourceRules")
                        .HasForeignKey("SourceProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jellywatch.Api.Domain.Profile", "TargetProfile")
                        .WithMany("TargetRules")
                        .HasForeignKey("TargetProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourceProfile");

                    b.Navigation("TargetProfile");
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.Season", b =>
                {
                    b.HasOne("Jellywatch.Api.Domain.Series", "Series")
                        .WithMany("Seasons")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Series");
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.Series", b =>
                {
                    b.HasOne("Jellywatch.Api.Domain.MediaItem", "MediaItem")
                        .WithOne("Series")
                        .HasForeignKey("Jellywatch.Api.Domain.Series", "MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaItem");
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.SyncJob", b =>
                {
                    b.HasOne("Jellywatch.Api.Domain.Profile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.UserWatchlistPreference", b =>
                {
                    b.HasOne("Jellywatch.Api.Domain.Watchlist", "DefaultWatchlist")
                        .WithMany()
                        .HasForeignKey("DefaultWatchlistId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Jellywatch.Api.Domain.User", "User")
                        .WithOne("WatchlistPreference")
                        .HasForeignKey("Jellywatch.Api.Domain.UserWatchlistPreference", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DefaultWatchlist");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.WatchEvent", b =>
                {
                    b.HasOne("Jellywatch.Api.Domain.Episode", "Episode")
                        .WithMany("WatchEvents")
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Jellywatch.Api.Domain.MediaItem", "MediaItem")
                        .WithMany()
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jellywatch.Api.Domain.Movie", "Movie")
                        .WithMany("WatchEvents")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Jellywatch.Api.Domain.Profile", "Profile")
                        .WithMany("WatchEvents")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Episode");

                    b.Navigation("MediaItem");

                    b.Navigation("Movie");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.Watchlist", b =>
                {
                    b.HasOne("Jellywatch.Api.Domain.User", "OwnerUser")
                        .WithMany("OwnedWatchlists")
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OwnerUser");
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.WatchlistAccessRequest", b =>
                {
                    b.HasOne("Jellywatch.Api.Domain.User", "RequestingUser")
                        .WithMany()
                        .HasForeignKey("RequestingUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jellywatch.Api.Domain.User", "RespondedByUser")
                        .WithMany()
                        .HasForeignKey("RespondedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Jellywatch.Api.Domain.Watchlist", "Watchlist")
                        .WithMany("AccessRequests")
                        .HasForeignKey("WatchlistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RequestingUser");

                    b.Navigation("RespondedByUser");

                    b.Navigation("Watchlist");
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.WatchlistInvitation", b =>
                {
                    b.HasOne("Jellywatch.Api.Domain.User", "InvitedByUser")
                        .WithMany()
                        .HasForeignKey("InvitedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jellywatch.Api.Domain.User", "InvitedUser")
                        .WithMany()
                        .HasForeignKey("InvitedUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jellywatch.Api.Domain.Watchlist", "Watchlist")
                        .WithMany("Invitations")
                        .HasForeignKey("WatchlistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InvitedByUser");

                    b.Navigation("InvitedUser");

                    b.Navigation("Watchlist");
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.WatchlistItem", b =>
                {
                    b.HasOne("Jellywatch.Api.Domain.User", "AddedByUser")
                        .WithMany()
                        .HasForeignKey("AddedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Jellywatch.Api.Domain.Watchlist", "ChildWatchlist")
                        .WithMany()
                        .HasForeignKey("ChildWatchlistId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Jellywatch.Api.Domain.MediaItem", "MediaItem")
                        .WithMany()
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Jellywatch.Api.Domain.Watchlist", "Watchlist")
                        .WithMany("Items")
                        .HasForeignKey("WatchlistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AddedByUser");

                    b.Navigation("ChildWatchlist");

                    b.Navigation("MediaItem");

                    b.Navigation("Watchlist");
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.WatchlistMember", b =>
                {
                    b.HasOne("Jellywatch.Api.Domain.User", "InvitedByUser")
                        .WithMany()
                        .HasForeignKey("InvitedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Jellywatch.Api.Domain.User", "User")
                        .WithMany("WatchlistMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jellywatch.Api.Domain.Watchlist", "Watchlist")
                        .WithMany("Members")
                        .HasForeignKey("WatchlistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InvitedByUser");

                    b.Navigation("User");

                    b.Navigation("Watchlist");
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.Episode", b =>
                {
                    b.Navigation("Notes");

                    b.Navigation("WatchEvents");

                    b.Navigation("WatchStates");
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.MediaItem", b =>
                {
                    b.Navigation("ExternalRatings");

                    b.Navigation("Images");

                    b.Navigation("Movie");

                    b.Navigation("Notes");

                    b.Navigation("Series");

                    b.Navigation("Translations");

                    b.Navigation("WatchStates");
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.Movie", b =>
                {
                    b.Navigation("WatchEvents");

                    b.Navigation("WatchStates");
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.Profile", b =>
                {
                    b.Navigation("Notes");

                    b.Navigation("SourceRules");

                    b.Navigation("TargetRules");

                    b.Navigation("WatchEvents");

                    b.Navigation("WatchStates");
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.Season", b =>
                {
                    b.Navigation("Episodes");

                    b.Navigation("Notes");
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.Series", b =>
                {
                    b.Navigation("Seasons");
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.User", b =>
                {
                    b.Navigation("OwnedWatchlists");

                    b.Navigation("Profiles");

                    b.Navigation("WatchlistMemberships");

                    b.Navigation("WatchlistPreference");
                });

            modelBuilder.Entity("Jellywatch.Api.Domain.Watchlist", b =>
                {
                    b.Navigation("AccessRequests");

                    b.Navigation("Invitations");

                    b.Navigation("Items");

                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
